### ISSUE TITLE
[FEAT][Request for help] Move Mkdocs website to new repo

### ISSUE THREAD

**Issue by tplessas** [zkotti/cosmos-tour#6]
## Proposal

I propose that the website found under the [mkdocs](https://github.com/zkotti/cosmos-tour/blob/main/mkdocs/) directory be moved to a separate repository (e.g. tplessas/cosmos-tour-website) and build automation be enabled.

## Rationale

As so pointedly put in [mkdocs/README.md](https://github.com/zkotti/cosmos-tour/blob/main/mkdocs/README.md), the website generated through the build process should not be located in this repo - it is a build artifact, not part of the source, and as such anyone can generate it at any time by simply going through the build process. Automating the build process on this repository would probably contribute more headaches to maintainers than value offered to the project.

Hosting static websites in GitHub repositories is officially supported by the service itself - anyone can create a *.github.io website using [GitHub Pages](https://pages.github.com/), often used for project documentation and simple personal sites.

Currently the website is not updated when changes in guide.md take place - this should not happen in this repository for the reasons explained in the first paragraph of this section, resulting in the website being significantly behind the actual guide since only this afternoon.

## Implementation

A new repo B will be created to host the website build. A GitHub Actions automation will be set up in this repo to dispatch an event to B whenever a push or a PR merge happens. Another automation on B will consume the event, fetch the files from repo A, and rebuild the website. The website will then be deployed on GitHub Pages, always up-to-date with the latest additions and fixes.

[This tutorial on the aforementioned automation pattern](https://blog.marcnuri.com/triggering-github-actions-across-different-repositories) could be used as a guide.

## Call for help

I can take this issue, but would appreciate some help from one more contributor as well - we could split up implementation into its two logical parts (the two automation scripts).

Going by my personal motto: "You can do most things in life by yourself, but it's more fun with friends."

**Comment by zkotti** [comment]
Great suggestion; well done! Look forward to seeing the implementation.

**Comment by tplessas** [comment]
@zkotti Glad to hear you're interested! We've set everything up on both repos, fully tested and in working order, with the website being accessible at https://e-panourgia.github.io/cosmos-tour/. Only thing left to do would be to add a personal access token to this repository from Settings>Secrets>New secret, which I will be e-mailing to you.

We will, for the time being, leave some build configuration files (mkdocs.yml, requirements.txt) on this repo, since we could not reach a consensus on what would be best practice on that front (in which repo they should be located) - if you have any relevant input we would be glad to take it into account.

We will, furthermore, not be immediately removing the mkdocs/site directory, as @NikosKakonas has made contributions to the website layout which would be lost in any other case - thankfully, as they mostly consist of HTML/CSS changes, the website template could be adapted to include them, or they could in part be included in mkdocs.yml under the `extra_css` key.

**Comment by zkotti** [comment]
@tplessas please see my comments below.

> @zkotti Glad to hear you're interested! We've set everything up on both repos, fully tested and in working order, with the website being accessible at https://e-panourgia.github.io/cosmos-tour/. Only thing left to do would be to add a personal access token to this repository from Settings>Secrets>New secret, which I will be e-mailing to you.

This has been completed. Please let me know if you need any further assistance from my side.

> We will, for the time being, leave some build configuration files (mkdocs.yml, requirements.txt) on this repo, since we could not reach a consensus on what would be best practice on that front (in which repo they should be located) - if you have any relevant input we would be glad to take it into account.

Since the website was moved to a new repository, I think these configuration files are now redundant here, so we can remove them.

> We will, furthermore, not be immediately removing the mkdocs/site directory, as @NikosKakonas has made contributions to the website layout which would be lost in any other case - thankfully, as they mostly consist of HTML/CSS changes, the website template could be adapted to include them, or they could in part be included in mkdocs.yml under the `extra_css` key.

Great! Feel free to close this issue once everything has been settled.

Again, well done to both of you as well as to anyone who contributed to the site! Amazing work!
